[package]
name = "fiab/no-jumping-zone"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.1.1-beta"
Knit = "sleitnick/knit@^1.2"
